"""
Generates the static config.h block and handles file I/O.
"""
import os
import re
import datetime
from typing import List, Dict, Any

def generate_config_block(inputs: List[Dict[str, Any]], platform: str, tool_version="1.0.0") -> str:
    """
    Generates the C++ block for static sensor configuration.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header = f"""
// ============================================================================
// STATIC SENSOR CONFIGURATION
// Generated by openEMS-config v{tool_version} on {timestamp}
// Platform: {platform}
// DO NOT EDIT MANUALLY - Use tools/configure.py to regenerate
// ============================================================================

#define NUM_CONFIGURED_INPUTS {len(inputs)}
"""

    input_defines = []
    for i, input_config in enumerate(inputs):
        app_name = input_config.get('application', 'NONE')
        sensor_name = input_config.get('sensor', 'NONE')

        define_block = f"""
// ----- Input {i}: {app_name} -----
#define INPUT_{i}_PIN           {input_config['pin']:<12}
#define INPUT_{i}_APPLICATION   {input_config['application_index']:<12} // {app_name}
#define INPUT_{i}_SENSOR        {input_config['sensor_index']:<12} // {sensor_name}
"""
        input_defines.append(define_block)

    return header + "".join(input_defines)

def update_config_h(config_h_path: str, new_block: str) -> bool:
    """
    Surgically replaces the static config block in config.h and creates a backup.
    Returns True on success, False on failure.
    """
    try:
        with open(config_h_path, 'r') as f:
            content = f.read()

        with open(config_h_path + ".bak", 'w') as f:
            f.write(content)

        start_marker = "#ifdef USE_STATIC_CONFIG"
        end_marker = "#endif // USE_STATIC_CONFIG"

        start_index = content.find(start_marker)
        end_index = content.find(end_marker)

        if start_index != -1 and end_index != -1:
            pre_block = content[:start_index + len(start_marker)]
            post_block = content[end_index:]
            new_content = pre_block + "\n" + new_block + "\n" + post_block
        else:
            final_endif_index = content.rfind("#endif")
            if final_endif_index != -1:
                pre_block = content[:final_endif_index]
                post_block = content[final_endif_index:]
                new_content = pre_block + start_marker + "\n" + new_block + "\n" + end_marker + "\n\n" + post_block
            else:
                new_content = content + "\n" + start_marker + "\n" + new_block + "\n" + end_marker + "\n"

        with open(config_h_path, 'w') as f:
            f.write(new_content)

        return True

    except IOError:
        return False

def generate_thin_library_files(
    inputs: List[Dict[str, Any]],
    sensors: List[Dict[str, Any]],
    applications: List[Dict[str, Any]],
    output_dir: str,
    project_dir: str
):
    """
    Generates thinned sensor and application library files, including only the
    PSTR macros and struct definitions that are actually used.
    """
    os.makedirs(output_dir, exist_ok=True)

    used_sensor_indices = {inp['sensor_index'] for inp in inputs}
    used_application_indices = {inp['application_index'] for inp in inputs}
    used_sensor_indices.add(0)
    used_application_indices.add(0)

    # Collect all required PSTR macros from the used sensors and applications
    required_pstr_macros = set()
    for sensor in sensors:
        if sensor['index'] in used_sensor_indices:
            required_pstr_macros.update(sensor['used_pstr_macros'])
    for app in applications:
        if app['index'] in used_application_indices:
            required_pstr_macros.update(app['used_pstr_macros'])

    # --- Generate thinned sensor library ---
    with open(os.path.join(project_dir, 'src/lib/sensor_library.h'), 'r') as f:
        sensor_template = f.read()

    pstr_def_pattern = re.compile(r'static const char (PSTR_\w+)\[\] PROGMEM = ".*?";')
    kept_pstr_defs = "\n".join(
        match.group(0) for match in pstr_def_pattern.finditer(sensor_template)
        if match.group(1) in required_pstr_macros
    )

    start_marker = "// ===== STRING LITERALS IN PROGMEM ====="
    end_marker = "// ===== SENSOR LIBRARY (PROGMEM - Flash Memory) ====="
    thinned_template = re.sub(
        rf'{re.escape(start_marker)}.*?{re.escape(end_marker)}',
        f'{start_marker}\n{kept_pstr_defs}\n\n{end_marker}',
        sensor_template,
        flags=re.DOTALL
    )

    sensor_structs_str = ",\n".join(
        s['raw_c_block'] for s in sorted(sensors, key=lambda x: x['index']) if s['index'] in used_sensor_indices
    )

    thinned_sensor_content = re.sub(
        r'(static const PROGMEM SensorInfo SENSOR_LIBRARY\[\] = \{)(.*?)(\};)',
        f'\\1\n{sensor_structs_str}\n\\3',
        thinned_template,
        flags=re.DOTALL
    )
    with open(os.path.join(output_dir, 'sensor_library_static.h'), 'w') as f:
        f.write(thinned_sensor_content)

    # --- Generate thinned application library ---
    with open(os.path.join(project_dir, 'src/lib/application_presets.h'), 'r') as f:
        app_template = f.read()

    kept_pstr_defs = "\n".join(
        match.group(0) for match in pstr_def_pattern.finditer(app_template)
        if match.group(1) in required_pstr_macros
    )

    start_marker = "// ===== STRING LITERALS IN PROGMEM ====="
    end_marker = "// ===== APPLICATION PRESETS (PROGMEM - Flash Memory) ====="
    thinned_template = re.sub(
        rf'{re.escape(start_marker)}.*?{re.escape(end_marker)}',
        f'{start_marker}\n{kept_pstr_defs}\n\n{end_marker}',
        app_template,
        flags=re.DOTALL
    )

    app_structs_str = ",\n".join(
        a['raw_c_block'] for a in sorted(applications, key=lambda x: x['index']) if a['index'] in used_application_indices
    )

    thinned_app_content = re.sub(
        r'(static const PROGMEM ApplicationPreset APPLICATION_PRESETS\[\] = \{)(.*?)(\};)',
        f'\\1\n{app_structs_str}\n\\3',
        thinned_template,
        flags=re.DOTALL
    )
    with open(os.path.join(output_dir, 'application_presets_static.h'), 'w') as f:
        f.write(thinned_app_content)
