#!/usr/bin/env python3
"""
openEMS Registry Enum Generator

Automatically generates C++ enum header file from sensor and application registries.
This provides type-safe, self-documenting constants instead of magic number indices.

Parses the modular sensor library structure:
  - src/lib/sensor_library.h (orchestrator)
  - src/lib/sensor_library/sensors/*.h (sensor definitions using X-macro pattern)
"""

import os
import sys
from datetime import datetime
from typing import List, Dict

# Ensure the script can find the openems_config package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '.')))

from openems_config.registry_parser import (
    parse_sensor_library,
    parse_application_presets
)


def generate_enum_header(sensors: List[Dict], apps: List[Dict], output_path: str) -> None:
    """
    Generate C++ enum header file from parsed registries.

    Args:
        sensors: List of sensor dictionaries from parse_sensor_library()
        apps: List of application dictionaries from parse_application_presets()
        output_path: Path where the header file should be written
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []
    lines.append("// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY")
    lines.append(f"// Generated by tools/generate_registry_enums.py")
    lines.append(f"// Last generated: {timestamp}")
    lines.append("")
    lines.append("#ifndef OPENEMS_REGISTRY_ENUMS_H")
    lines.append("#define OPENEMS_REGISTRY_ENUMS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    # Generate SensorIndex enum
    lines.append("// Sensor indices for SENSOR_LIBRARY array")
    lines.append("enum SensorIndex : uint8_t {")

    for index, sensor in enumerate(sensors):
        sensor_name = sensor['name']
        # Create enum constant name from sensor name (already in format like "MAX6675", "BME280_TEMP")
        enum_name = f"SENSOR_{sensor_name}"
        if index < len(sensors) - 1:
            lines.append(f"    {enum_name} = {index},")
        else:
            lines.append(f"    {enum_name} = {index}")

    lines.append("};")
    lines.append("")

    # Generate ApplicationIndex enum
    lines.append("// Application indices for APPLICATION_PRESETS array")
    lines.append("enum ApplicationIndex : uint8_t {")

    for index, app in enumerate(apps):
        app_name = app['name']
        # Create enum constant name from application name (already in format like "CHT", "COOLANT_TEMP")
        enum_name = f"APP_{app_name}"
        if index < len(apps) - 1:
            lines.append(f"    {enum_name} = {index},")
        else:
            lines.append(f"    {enum_name} = {index}")

    lines.append("};")
    lines.append("")
    lines.append("#endif // OPENEMS_REGISTRY_ENUMS_H")
    lines.append("")

    # Write to file
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Generated {output_path}")
    print(f"  - {len(sensors)} sensor constants")
    print(f"  - {len(apps)} application constants")


def main():
    """Main execution function."""
    # Determine paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_dir = os.path.dirname(script_dir)  # Parent of tools/ is project root

    sensor_lib_path = os.path.join(project_dir, "src/lib/sensor_library.h")
    app_presets_path = os.path.join(project_dir, "src/lib/application_presets.h")
    output_path = os.path.join(project_dir, "src/lib/generated/registry_enums.h")

    print("=== openEMS Registry Enum Generator ===")
    print(f"Project directory: {project_dir}")
    print()

    # Parse registries
    try:
        sensors = parse_sensor_library(sensor_lib_path)
        apps = parse_application_presets(app_presets_path)
    except FileNotFoundError as e:
        print(f"\u2717 Error: Could not find registry file. {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"\u2717 Error parsing registries: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"\u2713 Parsed {len(sensors)} sensors from sensor_library.h (+ sensor_library/sensors/)")
    print(f"\u2713 Parsed {len(apps)} applications from application_presets.h")
    print()

    # Generate enum header
    try:
        # Ensure output directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        generate_enum_header(sensors, apps, output_path)
        print()
        print(f"\u2713 Successfully generated registry_enums.h")

    except Exception as e:
        print(f"\u2717 Error generating enum header: {e}", file=sys.stderr)
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
