/*
 * advanced_config.h - Custom Sensor Calibrations
 *
 * This file is used for static builds (USE_STATIC_CONFIG) to define custom
 * sensor calibrations that override the default presets.
 *
 * USAGE:
 * Use tools/configure.py to generate custom calibrations automatically, or
 * manually define them below using the provided macros.
 *
 * See tools/README_ADVANCED_CONFIG.md for detailed documentation.
 */

#ifndef ADVANCED_CONFIG_H
#define ADVANCED_CONFIG_H

#include "config.h"  // For DEFAULT_BIAS_RESISTOR and other global defines
#include "lib/sensor_types.h"

// =============================================================================
// CALIBRATION MACROS
// =============================================================================

// Thermistor using Steinhart-Hart equation
// Usage: DEFINE_CUSTOM_THERMISTOR(name, bias_r, a, b, c)
#define DEFINE_CUSTOM_THERMISTOR(name, bias, a, b, c) \
    static const PROGMEM ThermistorSteinhartCalibration name##_custom_cal = { \
        .bias_resistor = bias, \
        .steinhart_a = a, \
        .steinhart_b = b, \
        .steinhart_c = c \
    };

// Pressure sensor using linear calibration
// Usage: DEFINE_CUSTOM_PRESSURE_LINEAR(name, v_min, v_max, p_min, p_max)
#define DEFINE_CUSTOM_PRESSURE_LINEAR(name, vmin, vmax, pmin, pmax) \
    static const PROGMEM LinearCalibration name##_custom_cal = { \
        .voltage_min = vmin, \
        .voltage_max = vmax, \
        .pressure_min = pmin, \
        .pressure_max = pmax \
    };

// Pressure sensor using polynomial calibration (VDO style)
// Usage: DEFINE_CUSTOM_PRESSURE_POLY(name, bias_r, poly_a, poly_b, poly_c)
#define DEFINE_CUSTOM_PRESSURE_POLY(name, bias, a, b, c) \
    static const PROGMEM PolynomialCalibration name##_custom_cal = { \
        .bias_resistor = bias, \
        .poly_a = a, \
        .poly_b = b, \
        .poly_c = c \
    };

// RPM sensor calibration
// Usage: DEFINE_CUSTOM_RPM(name, poles, pulley_ratio, calibration_mult, timeout, min, max)
#define DEFINE_CUSTOM_RPM(name, num_poles, ratio, mult, timeout, min_rpm, max_rpm) \
    static const PROGMEM RPMCalibration name##_custom_cal = { \
        .poles = num_poles, \
        .pulley_ratio = ratio, \
        .calibration_mult = mult, \
        .timeout_ms = timeout, \
        .min_rpm = min_rpm, \
        .max_rpm = max_rpm \
    };

// =============================================================================
// MANUAL CALIBRATION EXAMPLES
// =============================================================================

/*
// Example 1: Custom thermistor for Input 0 (Coolant Temperature)
#define INPUT_0_CUSTOM_CALIBRATION
#ifdef INPUT_0_CUSTOM_CALIBRATION
    DEFINE_CUSTOM_THERMISTOR(input_0,
        1000.0,      // bias_resistor
        1.129e-3,    // steinhart_a
        2.341e-4,    // steinhart_b
        8.775e-8     // steinhart_c
    )
#endif

// Example 2: Custom linear pressure sensor for Input 1 (Boost Pressure)
#define INPUT_1_CUSTOM_CALIBRATION
#ifdef INPUT_1_CUSTOM_CALIBRATION
    DEFINE_CUSTOM_PRESSURE_LINEAR(input_1,
        0.5,    // voltage_min
        4.5,    // voltage_max
        0.0,    // pressure_min (bar)
        3.0     // pressure_max (bar)
    )
#endif

// Example 3: Custom VDO polynomial sensor for Input 2 (Oil Pressure)
#define INPUT_2_CUSTOM_CALIBRATION
#ifdef INPUT_2_CUSTOM_CALIBRATION
    DEFINE_CUSTOM_PRESSURE_POLY(input_2,
        DEFAULT_BIAS_RESISTOR,  // bias_resistor
        -0.3682,                // poly_a
        36.465,                 // poly_b
        10.648                  // poly_c
    )
#endif

// Example 4: Custom RPM calibration for Input 3 (Engine RPM)
#define INPUT_3_CUSTOM_CALIBRATION
#ifdef INPUT_3_CUSTOM_CALIBRATION
    DEFINE_CUSTOM_RPM(input_3,
        18,      // poles (18-pole alternator)
        3.0,     // pulley_ratio (3:1 alternator to engine)
        1.0,     // calibration_mult
        2000,    // timeout_ms
        300,     // min_rpm
        8000     // max_rpm
    )
#endif
*/

// =============================================================================
// CUSTOM CALIBRATIONS
// =============================================================================
// This section is automatically generated by tools/configure.py
// Manual edits will be overwritten - use the configuration tool instead

// Add your manual custom calibrations below, or use tools/configure.py
// to generate them automatically

// =============================================================================
// AUTO-GENERATED CALIBRATIONS
// =============================================================================
// Include generated calibrations from tools/configure.py
#ifdef USE_STATIC_CONFIG
#if __has_include("lib/generated/static_calibrations.h")
#include "lib/generated/static_calibrations.h"
#endif
#endif

#endif // ADVANCED_CONFIG_H
